name: Register GitHub Self-Hosted Runner on EC2

on:
  workflow_dispatch:

jobs:
  ec2-runner-setup:
    runs-on: ubuntu-latest

    steps:
      - name: Get GitHub Runner Registration Token
        id: runner_token
        run: |
          REPO="your-username/your-repo"
          TOKEN=$(curl -s -X POST \
            -H "Authorization: token ${{ secrets.GH_PAT }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/$REPO/actions/runners/registration-token | jq -r .token)
          echo "::add-mask::$TOKEN"
          echo "token=$TOKEN" >> $GITHUB_OUTPUT

      - name: Setup GitHub Runner on EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo yum install -y curl jq git tar

            mkdir -p ~/actions-runner && cd ~/actions-runner

            ARCH=$(uname -m)
            RUNNER_ARCH="x64"
            if [ "$ARCH" = "aarch64" ]; then RUNNER_ARCH="arm64"; fi

            LATEST=$(curl -s https://api.github.com/repos/actions/runner/releases/latest \
              | jq -r ".assets[] | select(.name | test(\"linux-${RUNNER_ARCH}.tar.gz\")) | .browser_download_url")

            curl -O -L "$LATEST"
            tar xzf ./actions-runner-linux-${RUNNER_ARCH}.tar.gz

            ./config.sh \
              --url https://github.com/your-username/your-repo \
              --token ${{ steps.runner_token.outputs.token }} \
              --labels ec2 \
              --unattended \
              --replace

            sudo ./svc.sh install
            sudo ./svc.sh start
